<?php

/**
* @file
* Install, update and uninstall functions for the sta install profile.
*/

/**
* Implements hook_install().
*
* Perform actions to set up the site for this profile.
*
* @see system_install()
*/

function civicrm_website_i18n_install() {
  include_once DRUPAL_ROOT . '/profiles/standard/standard.install';
  standard_install();

  /*
  _civi_go_details();
  _civi_go_theme("theme783");
  _civi_go_blocks();
  _civi_go_locale();
  */
}
